name: Fetch Articles

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC
  workflow_dispatch:  

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests feedparser beautifulsoup4

      - name: Run article fetch script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}  # Inject API key
        run: python fetch_articles.py

      - name: Run source classification script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python classify_sources.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add articles.json last_fetch.json sources.json
          git commit -m "Updated articles and sources"
